flexyweb/urls.py
from django.conf import settings
from django.contrib import admin
from django.shortcuts import render
from my_auth import views as my_auth
from django.urls import path, include
from panel.sitemaps import *
from learn.admin import worker_admin_site
from panel.feeds import LatestCoursesFeed
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

admin.site.site_header = "Carrington Visionary Academy"
admin.site.site_title = "Carrington Visionary Academy Admin Portal"
admin.site.index_title = "Carrington Visionary Academy welcomes you!!!"
# worker_admin_site.site_header = "FlexyTuta"
# worker_admin_site.site_title = "FlexyTuta Admin Portal"
# worker_admin_site.index_title = "FlexyTuta welcomes you!!!"



sitemaps = {
 'courses': CourseSitemap,
 'static': StaticSitemap,
}

#handler404 = 'my_auth.handler404p'

urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('power/', admin.site.urls),
    path('tutors/', worker_admin_site.urls, name="tadmin"),
    #path('404-not-found/', my_auth.handler404p, name="handler404p"),
    path("", include("my_auth.urls")),
    path("contact/", include("contact.urls")),
    path("apply/", include("panel.urls")),
    path("cart/", include("cart.urls")),
    path("pay/", include("pay.urls")),
    path("learn/", include("learn.urls")),
    path("tutor/", include("tutor.urls")),
    # path("checkout/", include("cart.shop_urls")),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('feed/', LatestCoursesFeed(), name='course_feed'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pay/urls.py
from django.urls import path
from . import views as cart_views

urlpatterns = [
    path("payment/", cart_views.payment, name='yocoy'),
    path("yoco/", cart_views.payment_yoco, name='yoco_payment'),
    path("payfast/", cart_views.payfast, name='payfast'),
    path("mcard/", cart_views.paycard, name='mastercard'),
    path("yoco/", cart_views.yoco, name='yoco'),
    path("ozow/", cart_views.payozow, name='ozow'),
    path("paypal/", cart_views.paypal, name='paypal'),
    path("processing/", cart_views.pay_clear, name='ppaypal'),
    # path('paypal-payment-process/', cart_views.payment_processing, name='yoco'),
    path('before/', cart_views.pay_before, name='before'),
    path('done/', cart_views.payment_done, name='done'),
    path('canceled/', cart_views.payment_canceled, name='canceled'),
    path('notify/', cart_views.payfast_pay_clear, name='notify'),

    path('order/<int:pk>/', cart_views.OrderDetailView.as_view(), name="my_customer_order"),
    path('orders/', cart_views.my_orders, name="my_customer_orders"),
    # path('order/inv-no/<int:order_id>/', cart_views.admin_order_detail, name='admin_order_detail'),
    path('reciept/<int:order_id>', cart_views.invoice_order_detail, name='admin_order_detail'),
]

learn/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.urls import reverse
from learn.fields import OrderField
from flexyweb import settings
from panel.models import Course
# from PIL import Image
import PIL.Image
# Create your models here.
class Module(models.Model):
    course = models.ForeignKey(Course,
                               related_name='modules',
                               on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    order = OrderField(blank=True, for_fields=['course'])
    image = models.ImageField(default='modules/default.png', upload_to='modules/thumbnails', help_text='Make it a little bit bigger for cropping')
    students_completed = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='modules_completed', blank=True)
    
    class Meta:
        ordering = ['order']

    def __str__(self):
        return f'{self.order}. {self.title}'
    
    def is_user_in(self, request):
        if request.user in self.students_completed:
            return True
        return False
    
    def get_absolute_url(self):
        return reverse('course', 
            args=[self.course.publish.year,
            self.course.publish.month,
            self.course.publish.day,
            self.course.slug, self.pk])

    def save(self, *args, **kwargs):  # new
        super().save()
        img = PIL.Image.open(self.image.path)
        w, h = img.size
       
        if w < 400 or h < 400:
            del img
            self.image = "modules/default.png"
        else:
            img.thumbnail((400, 400))
            img.save(f"{self.image.path}")
        return super().save(*args, **kwargs)
    # def get_absolute_url(self):
    #     return reverse('module', args=[self.course.id, self.pk])



class Content(models.Model):
    module = models.ForeignKey(Module,
                               related_name='contents',
                               on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType,
                                     on_delete=models.CASCADE,
                                     limit_choices_to={'model__in':(
                                     'text',
                                     'video',
                                     'image',
                                     'eye',
                                     'file')})
    object_id = models.PositiveIntegerField()
    item = GenericForeignKey('content_type', 'object_id')
    order = OrderField(blank=True, for_fields=['module'])

    class Meta:
        ordering = ['order']


class ItemBase(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              related_name='%(class)s_related',
                              on_delete=models.CASCADE)
    module = models.ForeignKey(Module,
                               related_name='%(class)s_contents',
                               on_delete=models.CASCADE, default=2)
    title = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title


class Text(ItemBase):
    students_completed = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='text_completed', blank=True)
    content = models.TextField()


class File(ItemBase):
    students_completed = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='file_completed', blank=True)
    file = models.FileField(upload_to='modules/files')


class Image(ItemBase):
    students_completed = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='image_completed', blank=True)
    file = models.FileField(upload_to='modules/images')


class Video(ItemBase):
    students_completed = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='video_completed', blank=True)
    url = models.URLField()

class Eye(ItemBase):
    students_completed = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='eye_completed', blank=True)
    file = models.FileField(upload_to='modules/videos')

templates/auth_files/login.html
{% extends 'base.html' %}
<!--  -->
{% load static %}
<!--  -->
{% block content %}
<!--  -->

<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs" data-aos="fade-in">
        <div class="container">
            <h2>Sign in now</h2>
            <p>To continue, log in to {{ company }} </p>
        </div>
    </div>
    <!-- End Breadcrumbs -->
    {% if login_form.errors %}

    <div class="container">
        <!-- {% for error in form.errors %} -->
        <div class="alert">


            <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> {{login_form.errors}}

        </div>
        <!-- {% endfor %} -->
    </div>
    {% endif %}
    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">



        <div class="container" data-aos="fade-up">

            <div class="row mt-5">


                <div class="col-lg-4">

                </div>
                <div class="col-lg-4 mt-5 mt-lg-0">

                    <form action="{% url 'login' %}" method="post" role="form" enctype="multipart/form-data" class="php-email-form">
                        {% csrf_token %}

                        <div class="row">

                            {% for field in login_form %}

                            <div class="col-md-12 form-group m-2">
                                {{field}}
                                <!-- <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required> -->
                            </div>
                            {% endfor %}

                            <!-- <div class="col-md-6 form-group mt-3 mt-md-0">
                                {{form.first_name}}
                            </div> -->
                        </div>

                        <div class="form-group mt-3">
                            <!-- {{form.last_name}} -->
                            <!-- <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required> -->
                        </div>
                        <div class="form-group mt-3">
                            <!-- {{form.country}} -->
                            <!-- <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea> -->
                        </div>

                        {% if messages %}


                        <div class="my-3">
                            <div class="loading">Loading</div>
                            <div class="error-message"></div>
                            {% for message in messages %}
                            <div class="sent-message">Your message has been sent. Thank you!</div>
                            {% endfor %}
                        </div>
                        {% endif %}
                        <!-- <div class="text-center"><button type="submit">Login</button></div> -->
                        <!-- <div class="text-right ">
                            <a href="{% url 'password_reset' %}" class="forget-link">
								Forgot password?
							</a>
                        </div> -->
                        <div class="text-center">
                            <a href="{% url 'password_reset' %}" class="btn btn-light" data-mdb-ripple-color="blue">Forgot your password?</a>
                            <button type="submit" class="btn btn-dark">Login</button>
                            <!-- <div class="text-center m-3"><button href="{% url 'login' %}">Sign in</button></div> -->
                        </div>

                        <!-- <a href="{% url 'register' %}" class="btn btn-outline-light" data-mdb-ripple-color="blue">Don't have an account?</a> -->

                        <div class="text-center m-3"><a href="{% url 'register' %}">Don't have an account?</a></div>
                    </form>

                </div>
                <div class="col-lg-4">

                </div>

            </div>

        </div>
    </section>
    <!-- End Contact Section -->

</main>
<!-- End #main -->

{% endblock content %}

templates/auth_files/logout-success.html
{% extends 'base.html' %}
<!-- 

 -->
{% load static %}
<!--  -->
<div class="col-12">
    <h1>Logged Out - [@config:company_name@]</h1>
    <p>You have been successfully logged out of your account.</p>
    <p>
        <a class="btn btn-success btn-lg" href="[%url page:'account' type:'login'%][%/ url%]"><i class="fa fa-user"></i> Log in again</a>
    </p>
</div>

{% block content %}
<!--  -->

{% endblock content %}

templates/auth_files/photo_list.html
{% extends 'base.html' %}

{% block javascript %}
  <script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_file").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 200,
          minCropBoxHeight: 200,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#formUpload").submit();
      });

    });
  </script>
{% endblock %}

{% block content %}
  <h1 class="page-header">Album</h1>

  <!-- FORM TO UPLOAD THE IMAGES -->
  <form method="post" enctype="multipart/form-data" id="formUpload">
    {% csrf_token %}
    {{ form }}
  </form>

  <!-- MODAL TO CROP THE IMAGE -->
  <div class="modal fade" id="modalCrop">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">Crop the photo</h4>
        </div>
        <div class="modal-body">
          <img src="" id="image" style="max-width: 100%;">
        </div>
        <div class="modal-footer">
          <div class="btn-group pull-left" role="group">
            <button type="button" class="btn btn-default js-zoom-in">
              <span class="glyphicon glyphicon-zoom-in"></span>
            </button>
            <button type="button" class="btn btn-default js-zoom-out">
              <span class="glyphicon glyphicon-zoom-out"></span>
            </button>
          </div>
          <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
          <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
        </div>
      </div>
    </div>
  </div>

  <!-- CONTAINER TO DISPLAY THE CROPPED IMAGES -->
  <div class="row" style="margin-top: 20px">
    {% for photo in photos %}
      <div class="col-sm-4 col-md-3">
        <img src="{{ photo.file.url }}" class="thumbnail">
      </div>
    {% endfor %}
  </div>

{% endblock %}

templates/auth_files/profile_update.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1"> {% if title %}

    <title>{{title}}</title>
    {% else %}
    <title>MyTuta</title>
    {% endif %}
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="{% static 'css/cropper.min.css' %}" rel="stylesheet">
    <style type="text/css">
        .page-header {
            margin-top: 0;
        }
    </style>

</head>

<body>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
                <a class="navbar-brand" href="{% url 'profile' %}">Simple Image Crop</a>
            </div>
            <div class="collapse navbar-collapse" id="main-menu">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="https://simpleisbetterthancomplex.com">simpleisbetterthancomplex.com</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">


        <h1 class="page-header">Album</h1>

        <!-- FORM TO UPLOAD THE IMAGES -->
        <form method="post" enctype="multipart/form-data" id="formUpload">
            {% csrf_token %} {{ form }}
        </form>

        <!-- MODAL TO CROP THE IMAGE -->
        <div class="modal fade" id="modalCrop">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                        <h4 class="modal-title">Crop the photo</h4>
                    </div>
                    <div class="modal-body">
                        <img src="" id="image" style="max-width: 100%;">
                    </div>
                    <div class="modal-footer">
                        <div class="btn-group pull-left" role="group">
                            <button type="button" class="btn btn-default js-zoom-in">
                      <span class="glyphicon glyphicon-zoom-in"></span>
                    </button>
                            <button type="button" class="btn btn-default js-zoom-out">
                      <span class="glyphicon glyphicon-zoom-out"></span>
                    </button>
                        </div>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
                        <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
                    </div>
                </div>
            </div>
        </div>

        <!-- CONTAINER TO DISPLAY THE CROPPED IMAGES -->
        <div class="row" style="margin-top: 20px">
            <div class="col-sm-4 col-md-3">
                <img src="{{ request.profile.image.url }}" class="thumbnail">
            </div>
        </div>

    </div>
    <script src="{% static 'js/cr/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/cr/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/cr/cropper.min.js' %}"></script>
    <script>
        $(function() {

            /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
            $("#id_file").change(function() {
                if (this.files && this.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function(e) {
                        $("#image").attr("src", e.target.result);
                        $("#modalCrop").modal("show");
                    }
                    reader.readAsDataURL(this.files[0]);
                }
            });

            /* SCRIPTS TO HANDLE THE CROPPER BOX */
            var $image = $("#image");
            var cropBoxData;
            var canvasData;
            $("#modalCrop").on("shown.bs.modal", function() {
                $image.cropper({
                    viewMode: 1,
                    aspectRatio: 1 / 1,
                    minCropBoxWidth: 200,
                    minCropBoxHeight: 200,
                    ready: function() {
                        $image.cropper("setCanvasData", canvasData);
                        $image.cropper("setCropBoxData", cropBoxData);
                    }
                });
            }).on("hidden.bs.modal", function() {
                cropBoxData = $image.cropper("getCropBoxData");
                canvasData = $image.cropper("getCanvasData");
                $image.cropper("destroy");
            });

            $(".js-zoom-in").click(function() {
                $image.cropper("zoom", 0.1);
            });

            $(".js-zoom-out").click(function() {
                $image.cropper("zoom", -0.1);
            });

            /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
            $(".js-crop-and-upload").click(function() {
                var cropData = $image.cropper("getData");
                $("#id_x").val(cropData["x"]);
                $("#id_y").val(cropData["y"]);
                $("#id_height").val(cropData["height"]);
                $("#id_width").val(cropData["width"]);
                $("#formUpload").submit();
            });

        });
    </script>

</body>

</html>

templates/auth_files/student_register.html
{% extends 'base.html' %}
<!--  -->
{% load static %}
<!--  -->
{% block content %}
<!--  -->

<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs" data-aos="fade-in">
        <div class="container">
            <h2>Getting Started</h2>
            <p>You are about to register as a student </p>
        </div>
    </div>
    <!-- End Breadcrumbs -->
    {% if form.errors %}

    <div class="container">
        <!-- {% for error in form.errors %} -->
        <div class="alert">


            <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> {{form.errors}}

        </div>
        <!-- {% endfor %} -->
    </div>
    {% endif %}
    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">

        {% comment %}

        <div data-aos="fade-up">
            <iframe style="border:0; width: 100%; height: 350px;" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12097.433213460943!2d-74.0062269!3d40.7101282!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb89d1fe6bc499443!2sDowntown+Conference+Center!5e0!3m2!1smk!2sbg!4v1539943755621"
                frameborder="0" allowfullscreen></iframe>
        </div>
        {% endcomment %}


        <div class="container" data-aos="fade-up">

            <div class="row mt-5">

                {% comment %}

                <div class="col-lg-4">
                    <div class="info">
                        <div class="address">
                            <i class="bi bi-geo-alt"></i>
                            <h4>Location:</h4>
                            <p>A108 Adam Street, New York, NY 535022</p>
                        </div>

                        <div class="email">
                            <i class="bi bi-envelope"></i>
                            <h4>Email:</h4>
                            <p>info@example.com</p>
                        </div>

                        <div class="phone">
                            <i class="bi bi-phone"></i>
                            <h4>Call:</h4>
                            <p>+1 5589 55488 55s</p>
                        </div>

                    </div>

                </div>
                {% endcomment %}


                <div class="col-lg-4">

                </div>
                <div class="col-lg-4 mt-5 mt-lg-0">

                    <form action="{% url 'register' %}" method="post" role="form" enctype="multipart/form-data" class="php-email-form">
                        {% csrf_token %}

                        <div class="row">

                            {% for field in form %}

                            <div class="col-md-6 form-group">
                                {{field}}
                                <!-- <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required> -->
                            </div>
                            {% endfor %}


                        </div>

                        <div class="form-group mt-3">
                            <!-- {{form.last_name}} -->
                            <!-- <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required> -->
                        </div>
                        <div class="form-group mt-3">
                            <!-- {{form.country}} -->
                            <!-- <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea> -->
                        </div>

                        {% if messages %}


                        <div class="my-3">
                            <div class="loading">Loading</div>
                            <div class="error-message"></div>
                            {% for message in messages %}
                            <div class="sent-message">Your message has been sent. Thank you!</div>
                            {% endfor %}
                        </div>
                        {% endif %}
                        <div class="text-center"><button type="submit">Sign up</button></div>
                    </form>

                </div>
                <div class="col-lg-4">

                </div>

            </div>

        </div>
    </section>
    <!-- End Contact Section -->

</main>
<!-- End #main -->

{% endblock content %}